-- Add missing columns to Order table
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "metadata" JSONB DEFAULT '{}';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "type" TEXT;

-- Add missing columns to Status table
ALTER TABLE "Status" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Status" ADD COLUMN IF NOT EXISTS "color" VARCHAR(7);
ALTER TABLE "Status" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true;
ALTER TABLE "Status" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Status" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;